
x=int(input("Enter value of x "))
y=int(input("Enter value of y "))
z=int(input("Enter value of z "))
a=int(input("Enter value of a "))
b=int(input("Enter value of b "))

ans1=x+(y*z)
ans2=(x*y)+(a*b*b)
ans3=(a*a)+2*a*b+(b*b)
ans4=(a*a)-2*a*b+(b*b)
ans5=(a-b)*(a+b)
ans6=(a*a*a)+(b*b*b)+(3*a*b)*(a+b)
ans7=(a*a*a)-(b*b*b)-(3*a*b)*(a+b)
ans8=(a-b)*((a*a)+(a*b)+(b*b))
ans9=(a+b)*((a*a)-(a*b)+(b*b))
ans10=(3*x*y*y*y)+(9*x*x*y*y*y)+(5*y*y*y*x)

print("x+(y*z)" ,ans1)
print("(x*y)+(a*b*b)" ,ans2)
print("(a*a)+2*a*b+(b*b)" ,ans3)
print("(a*a)-2*a*b+(b*b)" ,ans4)
print("(a-b)*(a+b)" ,ans5)
print("(a*a*a)+(b*b*b)+(3*a*b)*(a+b)" ,ans6)
print("(a*a*a)-(b*b*b)-(3*a*b)*(a+b)" ,ans7)
print("(a-b)*((a*a)+(a*b)+(b*b))" ,ans8)
print("(a+b)*((a*a)-(a*b)+(b*b))" ,ans9)
print("(3*x*y*y*y)+(9*x*x*y*y*y)+(5*y*y*y*x)" ,ans10)

